// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: rollkit/v1/state_rpc.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block contains all the components of a complete block
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *SignedHeader          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_state_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeader() *SignedHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetBlockRequest defines the request for retrieving a block
type GetBlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The height or hash of the block to retrieve
	//
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetBlockRequest_Height
	//	*GetBlockRequest_Hash
	Identifier    isGetBlockRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_state_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetBlockRequest) GetIdentifier() isGetBlockRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetBlockRequest) GetHeight() uint64 {
	if x != nil {
		if x, ok := x.Identifier.(*GetBlockRequest_Height); ok {
			return x.Height
		}
	}
	return 0
}

func (x *GetBlockRequest) GetHash() []byte {
	if x != nil {
		if x, ok := x.Identifier.(*GetBlockRequest_Hash); ok {
			return x.Hash
		}
	}
	return nil
}

type isGetBlockRequest_Identifier interface {
	isGetBlockRequest_Identifier()
}

type GetBlockRequest_Height struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3,oneof"`
}

type GetBlockRequest_Hash struct {
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3,oneof"`
}

func (*GetBlockRequest_Height) isGetBlockRequest_Identifier() {}

func (*GetBlockRequest_Hash) isGetBlockRequest_Identifier() {}

// GetBlockResponse defines the response for retrieving a block
type GetBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_state_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// GetStateResponse defines the response for retrieving the current state
type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_state_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetStateResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

// GetMetadataRequest defines the request for retrieving metadata by key
type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_state_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetadataRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetMetadataResponse defines the response for retrieving metadata
type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_state_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetadataResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// MetadataKey describes a metadata key with its description
type MetadataKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataKey) Reset() {
	*x = MetadataKey{}
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataKey) ProtoMessage() {}

func (x *MetadataKey) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataKey.ProtoReflect.Descriptor instead.
func (*MetadataKey) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_state_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *MetadataKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataKey) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ListMetadataKeysResponse defines the response for listing metadata keys
type ListMetadataKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*MetadataKey         `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetadataKeysResponse) Reset() {
	*x = ListMetadataKeysResponse{}
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetadataKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetadataKeysResponse) ProtoMessage() {}

func (x *ListMetadataKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetadataKeysResponse.ProtoReflect.Descriptor instead.
func (*ListMetadataKeysResponse) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_state_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *ListMetadataKeysResponse) GetKeys() []*MetadataKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

// MetadataEntry represents a key-value pair of metadata
type MetadataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataEntry) Reset() {
	*x = MetadataEntry{}
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataEntry) ProtoMessage() {}

func (x *MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataEntry.ProtoReflect.Descriptor instead.
func (*MetadataEntry) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_state_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *MetadataEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// GetAllMetadataResponse defines the response for retrieving all metadata
type GetAllMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      []*MetadataEntry       `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMetadataResponse) Reset() {
	*x = GetAllMetadataResponse{}
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMetadataResponse) ProtoMessage() {}

func (x *GetAllMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_state_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetAllMetadataResponse) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_state_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllMetadataResponse) GetMetadata() []*MetadataEntry {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_rollkit_v1_state_rpc_proto protoreflect.FileDescriptor

const file_rollkit_v1_state_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1arollkit/v1/state_rpc.proto\x12\n" +
	"rollkit.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18rollkit/v1/rollkit.proto\x1a\x16rollkit/v1/state.proto\"_\n" +
	"\x05Block\x120\n" +
	"\x06header\x18\x01 \x01(\v2\x18.rollkit.v1.SignedHeaderR\x06header\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.rollkit.v1.DataR\x04data\"O\n" +
	"\x0fGetBlockRequest\x12\x18\n" +
	"\x06height\x18\x01 \x01(\x04H\x00R\x06height\x12\x14\n" +
	"\x04hash\x18\x02 \x01(\fH\x00R\x04hashB\f\n" +
	"\n" +
	"identifier\";\n" +
	"\x10GetBlockResponse\x12'\n" +
	"\x05block\x18\x01 \x01(\v2\x11.rollkit.v1.BlockR\x05block\";\n" +
	"\x10GetStateResponse\x12'\n" +
	"\x05state\x18\x01 \x01(\v2\x11.rollkit.v1.StateR\x05state\"&\n" +
	"\x12GetMetadataRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"+\n" +
	"\x13GetMetadataResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"A\n" +
	"\vMetadataKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"G\n" +
	"\x18ListMetadataKeysResponse\x12+\n" +
	"\x04keys\x18\x01 \x03(\v2\x17.rollkit.v1.MetadataKeyR\x04keys\"7\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"O\n" +
	"\x16GetAllMetadataResponse\x125\n" +
	"\bmetadata\x18\x01 \x03(\v2\x19.rollkit.v1.MetadataEntryR\bmetadata2\x91\x03\n" +
	"\fStoreService\x12G\n" +
	"\bGetBlock\x12\x1b.rollkit.v1.GetBlockRequest\x1a\x1c.rollkit.v1.GetBlockResponse\"\x00\x12B\n" +
	"\bGetState\x12\x16.google.protobuf.Empty\x1a\x1c.rollkit.v1.GetStateResponse\"\x00\x12P\n" +
	"\vGetMetadata\x12\x1e.rollkit.v1.GetMetadataRequest\x1a\x1f.rollkit.v1.GetMetadataResponse\"\x00\x12R\n" +
	"\x10ListMetadataKeys\x12\x16.google.protobuf.Empty\x1a$.rollkit.v1.ListMetadataKeysResponse\"\x00\x12N\n" +
	"\x0eGetAllMetadata\x12\x16.google.protobuf.Empty\x1a\".rollkit.v1.GetAllMetadataResponse\"\x00B0Z.github.com/rollkit/rollkit/types/pb/rollkit/v1b\x06proto3"

var (
	file_rollkit_v1_state_rpc_proto_rawDescOnce sync.Once
	file_rollkit_v1_state_rpc_proto_rawDescData []byte
)

func file_rollkit_v1_state_rpc_proto_rawDescGZIP() []byte {
	file_rollkit_v1_state_rpc_proto_rawDescOnce.Do(func() {
		file_rollkit_v1_state_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rollkit_v1_state_rpc_proto_rawDesc), len(file_rollkit_v1_state_rpc_proto_rawDesc)))
	})
	return file_rollkit_v1_state_rpc_proto_rawDescData
}

var file_rollkit_v1_state_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rollkit_v1_state_rpc_proto_goTypes = []any{
	(*Block)(nil),                    // 0: rollkit.v1.Block
	(*GetBlockRequest)(nil),          // 1: rollkit.v1.GetBlockRequest
	(*GetBlockResponse)(nil),         // 2: rollkit.v1.GetBlockResponse
	(*GetStateResponse)(nil),         // 3: rollkit.v1.GetStateResponse
	(*GetMetadataRequest)(nil),       // 4: rollkit.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil),      // 5: rollkit.v1.GetMetadataResponse
	(*MetadataKey)(nil),              // 6: rollkit.v1.MetadataKey
	(*ListMetadataKeysResponse)(nil), // 7: rollkit.v1.ListMetadataKeysResponse
	(*MetadataEntry)(nil),            // 8: rollkit.v1.MetadataEntry
	(*GetAllMetadataResponse)(nil),   // 9: rollkit.v1.GetAllMetadataResponse
	(*SignedHeader)(nil),             // 10: rollkit.v1.SignedHeader
	(*Data)(nil),                     // 11: rollkit.v1.Data
	(*State)(nil),                    // 12: rollkit.v1.State
	(*emptypb.Empty)(nil),            // 13: google.protobuf.Empty
}
var file_rollkit_v1_state_rpc_proto_depIdxs = []int32{
	10, // 0: rollkit.v1.Block.header:type_name -> rollkit.v1.SignedHeader
	11, // 1: rollkit.v1.Block.data:type_name -> rollkit.v1.Data
	0,  // 2: rollkit.v1.GetBlockResponse.block:type_name -> rollkit.v1.Block
	12, // 3: rollkit.v1.GetStateResponse.state:type_name -> rollkit.v1.State
	6,  // 4: rollkit.v1.ListMetadataKeysResponse.keys:type_name -> rollkit.v1.MetadataKey
	8,  // 5: rollkit.v1.GetAllMetadataResponse.metadata:type_name -> rollkit.v1.MetadataEntry
	1,  // 6: rollkit.v1.StoreService.GetBlock:input_type -> rollkit.v1.GetBlockRequest
	13, // 7: rollkit.v1.StoreService.GetState:input_type -> google.protobuf.Empty
	4,  // 8: rollkit.v1.StoreService.GetMetadata:input_type -> rollkit.v1.GetMetadataRequest
	13, // 9: rollkit.v1.StoreService.ListMetadataKeys:input_type -> google.protobuf.Empty
	13, // 10: rollkit.v1.StoreService.GetAllMetadata:input_type -> google.protobuf.Empty
	2,  // 11: rollkit.v1.StoreService.GetBlock:output_type -> rollkit.v1.GetBlockResponse
	3,  // 12: rollkit.v1.StoreService.GetState:output_type -> rollkit.v1.GetStateResponse
	5,  // 13: rollkit.v1.StoreService.GetMetadata:output_type -> rollkit.v1.GetMetadataResponse
	7,  // 14: rollkit.v1.StoreService.ListMetadataKeys:output_type -> rollkit.v1.ListMetadataKeysResponse
	9,  // 15: rollkit.v1.StoreService.GetAllMetadata:output_type -> rollkit.v1.GetAllMetadataResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_rollkit_v1_state_rpc_proto_init() }
func file_rollkit_v1_state_rpc_proto_init() {
	if File_rollkit_v1_state_rpc_proto != nil {
		return
	}
	file_rollkit_v1_rollkit_proto_init()
	file_rollkit_v1_state_proto_init()
	file_rollkit_v1_state_rpc_proto_msgTypes[1].OneofWrappers = []any{
		(*GetBlockRequest_Height)(nil),
		(*GetBlockRequest_Hash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rollkit_v1_state_rpc_proto_rawDesc), len(file_rollkit_v1_state_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rollkit_v1_state_rpc_proto_goTypes,
		DependencyIndexes: file_rollkit_v1_state_rpc_proto_depIdxs,
		MessageInfos:      file_rollkit_v1_state_rpc_proto_msgTypes,
	}.Build()
	File_rollkit_v1_state_rpc_proto = out.File
	file_rollkit_v1_state_rpc_proto_goTypes = nil
	file_rollkit_v1_state_rpc_proto_depIdxs = nil
}
